<?php

namespace Proxies\__CG__\App\PartNumbers\DomainPartNumbers\DomainModelPartNumbers\EntityPartNumbers;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PartNumbersFromManufacturers extends \App\PartNumbers\DomainPartNumbers\DomainModelPartNumbers\EntityPartNumbers\PartNumbersFromManufacturers implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'additional_descriptions' => [parent::class, 'additional_descriptions', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_axle' => [parent::class, 'id_axle', null],
        "\0".parent::class."\0".'id_body' => [parent::class, 'id_body', null],
        "\0".parent::class."\0".'id_car_brand' => [parent::class, 'id_car_brand', null],
        "\0".parent::class."\0".'id_in_stock' => [parent::class, 'id_in_stock', null],
        "\0".parent::class."\0".'id_original_number' => [parent::class, 'id_original_number', null],
        "\0".parent::class."\0".'id_part_name' => [parent::class, 'id_part_name', null],
        "\0".parent::class."\0".'id_side' => [parent::class, 'id_side', null],
        "\0".parent::class."\0".'manufacturer' => [parent::class, 'manufacturer', null],
        "\0".parent::class."\0".'part_number' => [parent::class, 'part_number', null],
        'additional_descriptions' => [parent::class, 'additional_descriptions', null],
        'id' => [parent::class, 'id', null],
        'id_axle' => [parent::class, 'id_axle', null],
        'id_body' => [parent::class, 'id_body', null],
        'id_car_brand' => [parent::class, 'id_car_brand', null],
        'id_in_stock' => [parent::class, 'id_in_stock', null],
        'id_original_number' => [parent::class, 'id_original_number', null],
        'id_part_name' => [parent::class, 'id_part_name', null],
        'id_side' => [parent::class, 'id_side', null],
        'manufacturer' => [parent::class, 'manufacturer', null],
        'part_number' => [parent::class, 'part_number', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
