<?php

namespace Proxies\__CG__\App\Counterparty\DomainCounterparty\DomainModelCounterparty\EntityCounterparty;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Counterparty extends \App\Counterparty\DomainCounterparty\DomainModelCounterparty\EntityCounterparty\Counterparty implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'delivery_phone' => [parent::class, 'delivery_phone', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'mail_counterparty' => [parent::class, 'mail_counterparty', null],
        "\0".parent::class."\0".'manager_phone' => [parent::class, 'manager_phone', null],
        "\0".parent::class."\0".'name_counterparty' => [parent::class, 'name_counterparty', null],
        'delivery_phone' => [parent::class, 'delivery_phone', null],
        'id' => [parent::class, 'id', null],
        'mail_counterparty' => [parent::class, 'mail_counterparty', null],
        'manager_phone' => [parent::class, 'manager_phone', null],
        'name_counterparty' => [parent::class, 'name_counterparty', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
