<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdapterAutoPartsWarehousePartNumbersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehousePartNumbers' shared autowired service.
     *
     * @return \App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehousePartNumbers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/AdapterAutoPartsWarehouse/AdapterAutoPartsWarehousePartNumbersInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/AdapterAutoPartsWarehouse/AdapterAutoPartsWarehousePartNumbers.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/QueryPartNumbers/SearchPartNumbersQuery/FindOneByPartNumbersQueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/QueryPartNumbers/SearchPartNumbersQuery/FindOneByPartNameQueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/ErrorsPartNumbers/InputErrorsPartNumbers.php';

        $a = ($container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\RepositoryPartNumbers\\PartNumbersFromManufacturersRepository'] ?? $container->load('getPartNumbersFromManufacturersRepositoryService'));

        return $container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\AdapterAutoPartsWarehouse\\AdapterAutoPartsWarehousePartNumbers'] = new \App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehousePartNumbers($a, new \App\PartNumbers\ApplicationPartNumbers\QueryPartNumbers\SearchPartNumbersQuery\FindOneByPartNumbersQueryHandler(($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\ErrorsPartNumbers\\InputErrorsPartNumbers'] ??= new \App\PartNumbers\ApplicationPartNumbers\ErrorsPartNumbers\InputErrorsPartNumbers()), $a), ($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\SavePartNumbersCommand\\SavePartNumbersCommandHandler'] ?? $container->load('getSavePartNumbersCommandHandlerService')), ($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\EditPartNumbersQuery\\FindIdPartNumbersQueryHandler'] ?? $container->load('getFindIdPartNumbersQueryHandlerService')), new \App\PartNumbers\ApplicationPartNumbers\QueryPartNumbers\SearchPartNumbersQuery\FindOneByPartNameQueryHandler(($container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\RepositoryPartNumbers\\PartNameRepository'] ?? $container->load('getPartNameRepositoryService'))));
    }
}
