<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterpartyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Counterparty\InfrastructureCounterparty\ApiCounterparty\ControllerCounterparty\CounterpartyController' shared autowired service.
     *
     * @return \App\Counterparty\InfrastructureCounterparty\ApiCounterparty\ControllerCounterparty\CounterpartyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Counterparty/InfrastructureCounterparty/ApiCounterparty/ControllerCounterparty/CounterpartyController.php';

        $container->services['App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController'] = $instance = new \App\Counterparty\InfrastructureCounterparty\ApiCounterparty\ControllerCounterparty\CounterpartyController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController', $container));

        return $instance;
    }
}
