<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterpartyControllersaveCounterpartyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ccKJiTH.App\Counterparty\InfrastructureCounterparty\ApiCounterparty\ControllerCounterparty\CounterpartyController::saveCounterparty()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ccKJiTH.App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController::saveCounterparty()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'saveCounterpartyCommandHandler' => ['privates', 'App\\Counterparty\\ApplicationCounterparty\\CommandsCounterparty\\SaveCounterpartyCommand\\SaveCounterpartyCommandHandler', 'getSaveCounterpartyCommandHandlerService', true],
        ], [
            'saveCounterpartyCommandHandler' => 'App\\Counterparty\\ApplicationCounterparty\\CommandsCounterparty\\SaveCounterpartyCommand\\SaveCounterpartyCommandHandler',
        ]))->withContext('App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController::saveCounterparty()', $container);
    }
}
