<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterpartyRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Counterparty\InfrastructureCounterparty\RepositoryCounterparty\CounterpartyRepository' shared autowired service.
     *
     * @return \App\Counterparty\InfrastructureCounterparty\RepositoryCounterparty\CounterpartyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Counterparty/DomainCounterparty/RepositoryInterfaceCounterparty/CounterpartyRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Counterparty/InfrastructureCounterparty/RepositoryCounterparty/CounterpartyRepository.php';

        return $container->privates['App\\Counterparty\\InfrastructureCounterparty\\RepositoryCounterparty\\CounterpartyRepository'] = new \App\Counterparty\InfrastructureCounterparty\RepositoryCounterparty\CounterpartyRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
