<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorMessageViaSessionerrorMessageSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HWI0Oe0.App\PartNumbers\InfrastructurePartNumbers\ErrorMessageViaSession\ErrorMessageViaSession::errorMessageSession()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HWI0Oe0.App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession::errorMessageSession()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'e' => ['privates', '.errored..service_locator.HWI0Oe0.Symfony\\Component\\HttpKernel\\Exception\\HttpException', NULL, 'Cannot autowire service ".service_locator.HWI0Oe0": it references class "Symfony\\Component\\HttpKernel\\Exception\\HttpException" but no such service exists.'],
        ], [
            'e' => 'Symfony\\Component\\HttpKernel\\Exception\\HttpException',
        ]))->withContext('App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession::errorMessageSession()', $container);
    }
}
