<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorMessageViaSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\PartNumbers\InfrastructurePartNumbers\ErrorMessageViaSession\ErrorMessageViaSession' shared autowired service.
     *
     * @return \App\PartNumbers\InfrastructurePartNumbers\ErrorMessageViaSession\ErrorMessageViaSession
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/InfrastructurePartNumbers/ErrorMessageViaSession/ErrorMessageViaSession.php';

        $container->services['App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession'] = $instance = new \App\PartNumbers\InfrastructurePartNumbers\ErrorMessageViaSession\ErrorMessageViaSession();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession', $container));

        return $instance;
    }
}
