<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityHiddenTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\EntityHiddenType' shared autowired service.
     *
     * @return \App\Form\Type\EntityHiddenType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Core/Type/HiddenType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/EntityHiddenType.php';

        return $container->privates['App\\Form\\Type\\EntityHiddenType'] = new \App\Form\Type\EntityHiddenType();
    }
}
