<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAutoPartsWarehouseQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\EditAutoPartsWarehouseQuery\FindAutoPartsWarehouseQueryHandler' shared autowired service.
     *
     * @return \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\EditAutoPartsWarehouseQuery\FindAutoPartsWarehouseQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/ApplicationAutoPartsWarehouse/QueryAutoPartsWarehouse/EditAutoPartsWarehouseQuery/FindAutoPartsWarehouseQueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/ApplicationAutoPartsWarehouse/ErrorsAutoPartsWarehouse/InputErrorsAutoPartsWarehouse.php';

        return $container->privates['App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\QueryAutoPartsWarehouse\\EditAutoPartsWarehouseQuery\\FindAutoPartsWarehouseQueryHandler'] = new \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\EditAutoPartsWarehouseQuery\FindAutoPartsWarehouseQueryHandler(($container->privates['App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\ErrorsAutoPartsWarehouse\\InputErrorsAutoPartsWarehouse'] ??= new \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\ErrorsAutoPartsWarehouse\InputErrorsAutoPartsWarehouse()), ($container->privates['App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\RepositoryAutoPartsWarehouse\\AutoPartsWarehouseRepository'] ?? $container->load('getAutoPartsWarehouseRepositoryService')));
    }
}
