<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindByCartAutoPartsSoldQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\ApplicationSales\QuerySales\ListCartAutoParts\FindByCartAutoPartsSoldQueryHandler' shared autowired service.
     *
     * @return \App\Sales\ApplicationSales\QuerySales\ListCartAutoParts\FindByCartAutoPartsSoldQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/QuerySales/ListCartAutoParts/FindByCartAutoPartsSoldQueryHandler.php';

        return $container->privates['App\\Sales\\ApplicationSales\\QuerySales\\ListCartAutoParts\\FindByCartAutoPartsSoldQueryHandler'] = new \App\Sales\ApplicationSales\QuerySales\ListCartAutoParts\FindByCartAutoPartsSoldQueryHandler(($container->privates['App\\Sales\\InfrastructureSales\\RepositorySales\\AutoPartsSoldRepository'] ?? $container->load('getAutoPartsSoldRepositoryService')));
    }
}
