<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllereditСartAutoPartsWarehouseSoldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F7g8s_2.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::editСartAutoPartsWarehouseSold()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F7g8s_2.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::editСartAutoPartsWarehouseSold()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findСartAutoPartsSoldQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\EditСartAutoPartsSold\\FindСartAutoPartsSoldQueryHandler', 'getFindСartAutoPartsSoldQueryHandlerService', true],
            'editCartAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\EditCartAutoPartsCommand\\EditCartAutoPartsCommandHandler', 'getEditCartAutoPartsCommandHandlerService', true],
        ], [
            'findСartAutoPartsSoldQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\EditСartAutoPartsSold\\FindСartAutoPartsSoldQueryHandler',
            'editCartAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\EditCartAutoPartsCommand\\EditCartAutoPartsCommandHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::editСartAutoPartsWarehouseSold()', $container);
    }
}
