<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllereditSalesAutoPartsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AxXH9uZ.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::editSalesAutoParts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AxXH9uZ.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::editSalesAutoParts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findOneBySalesAutoPartsQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\EditSalesAutoParts\\FindOneBySalesAutoPartsQueryHandler', 'getFindOneBySalesAutoPartsQueryHandlerService', true],
            'editSalesAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\EditSalesAutoPartsCommand\\EditSalesAutoPartsCommandHandler', 'getEditSalesAutoPartsCommandHandlerService', true],
        ], [
            'findOneBySalesAutoPartsQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\EditSalesAutoParts\\FindOneBySalesAutoPartsQueryHandler',
            'editSalesAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\EditSalesAutoPartsCommand\\EditSalesAutoPartsCommandHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::editSalesAutoParts()', $container);
    }
}
