<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllercompletionSaleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iyDxjkZ.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::completionSale()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iyDxjkZ.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::completionSale()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'completionSaleAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\CompletionSaleAutoPartsCommand\\CompletionSaleAutoPartsCommandHandler', 'getCompletionSaleAutoPartsCommandHandlerService', true],
        ], [
            'completionSaleAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\CompletionSaleAutoPartsCommand\\CompletionSaleAutoPartsCommandHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::completionSale()', $container);
    }
}
