<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaveOriginalRoomsCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\SavePartNumbersCommand\SaveOriginalRoomsCommandHandler' shared autowired service.
     *
     * @return \App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\SavePartNumbersCommand\SaveOriginalRoomsCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/CommandsPartNumbers/SavePartNumbersCommand/SaveOriginalRoomsCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/DomainPartNumbers/DomainModelPartNumbers/EntityPartNumbers/OriginalRooms.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/ErrorsPartNumbers/InputErrorsPartNumbers.php';

        return $container->privates['App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\SavePartNumbersCommand\\SaveOriginalRoomsCommandHandler'] = new \App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\SavePartNumbersCommand\SaveOriginalRoomsCommandHandler(($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\ErrorsPartNumbers\\InputErrorsPartNumbers'] ??= new \App\PartNumbers\ApplicationPartNumbers\ErrorsPartNumbers\InputErrorsPartNumbers()), ($container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\RepositoryPartNumbers\\OriginalRoomsRepository'] ?? $container->load('getOriginalRoomsRepositoryService')), new \App\PartNumbers\DomainPartNumbers\DomainModelPartNumbers\EntityPartNumbers\OriginalRooms());
    }
}
