<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllerdeleteSalesAutoPartsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b_daz4a.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::deleteSalesAutoParts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b_daz4a.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::deleteSalesAutoParts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteSalesAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\DeleteSalesAutoPartsCommand\\DeleteSalesAutoPartsCommandHandler', 'getDeleteSalesAutoPartsCommandHandlerService', true],
        ], [
            'deleteSalesAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\DeleteSalesAutoPartsCommand\\DeleteSalesAutoPartsCommandHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::deleteSalesAutoParts()', $container);
    }
}
