<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllersearchSalesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NHNcKxb.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::searchSales()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NHNcKxb.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::searchSales()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findBySalesQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\SearchSalesQuery\\FindBySalesQueryHandler', 'getFindBySalesQueryHandlerService', true],
            'findBySalesToDateQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\SalesToDate\\FindBySalesToDateQueryHandler', 'getFindBySalesToDateQueryHandlerService', true],
        ], [
            'findBySalesQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\SearchSalesQuery\\FindBySalesQueryHandler',
            'findBySalesToDateQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\SalesToDate\\FindBySalesToDateQueryHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::searchSales()', $container);
    }
}
