<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchPartNumbersTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\FormPartNumbers\SearchPartNumbersType' shared autowired service.
     *
     * @return \App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\FormPartNumbers\SearchPartNumbersType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/FormPartNumbers/SearchPartNumbersType.php';

        return $container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\FormPartNumbers\\SearchPartNumbersType'] = new \App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\FormPartNumbers\SearchPartNumbersType();
    }
}
