<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllercartAutoPartsWarehouseSoldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Shy7JIl.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::cartAutoPartsWarehouseSold()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Shy7JIl.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::cartAutoPartsWarehouseSold()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adapterSalesInterface' => ['privates', 'App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\ApiAutoPartsWarehouse\\Adapters\\AdapterSales\\AdapterSales', 'getAdapterSalesService', true],
            'addCartAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\AddCartAutoPartsCommand\\AddCartAutoPartsCommandHandler', 'getAddCartAutoPartsCommandHandlerService', true],
            'findByCartAutoPartsSoldQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\ListCartAutoParts\\FindByCartAutoPartsSoldQueryHandler', 'getFindByCartAutoPartsSoldQueryHandlerService', true],
        ], [
            'adapterSalesInterface' => '?',
            'addCartAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\AddCartAutoPartsCommand\\AddCartAutoPartsCommandHandler',
            'findByCartAutoPartsSoldQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\ListCartAutoParts\\FindByCartAutoPartsSoldQueryHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::cartAutoPartsWarehouseSold()', $container);
    }
}
