<?php

namespace ContainerM9s1qO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidateConnectionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SecIT\ImapBundle\Command\ValidateConnectionsCommand' shared autowired service.
     *
     * @return \SecIT\ImapBundle\Command\ValidateConnectionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/secit-pl/imap-bundle/Command/ValidateConnectionsCommand.php';

        $container->privates['SecIT\\ImapBundle\\Command\\ValidateConnectionsCommand'] = $instance = new \SecIT\ImapBundle\Command\ValidateConnectionsCommand(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['secit.imap.connection.example'] ?? $container->load('getSecit_Imap_Connection_ExampleService'));
        }, 1));

        $instance->setName('secit:imap:validate-connections');
        $instance->setDescription('Validate if all Mailboxes can connect correct. If not, return 1.');

        return $instance;
    }
}
