<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutoPartsWarehouseControllersaveAutoPartsManuallyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OGWRibG.App\AutoPartsWarehouse\InfrastructureAutoPartsWarehouse\ApiAutoPartsWarehouse\ControllerAutoPartsWarehouse\AutoPartsWarehouseController::saveAutoPartsManually()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OGWRibG.App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\ApiAutoPartsWarehouse\\ControllerAutoPartsWarehouse\\AutoPartsWarehouseController::saveAutoPartsManually()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'saveAutoPartsWarehouseCommandHandler' => ['privates', 'App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\CommandsAutoPartsWarehouse\\SaveAutoPartsWarehouseCommand\\SaveAutoPartsWarehouseCommandHandler', 'getSaveAutoPartsWarehouseCommandHandlerService', true],
            'adapterAutoPartsWarehousePartNumbersInterface' => ['privates', 'App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\AdapterAutoPartsWarehouse\\AdapterAutoPartsWarehousePartNumbers', 'getAdapterAutoPartsWarehousePartNumbersService', true],
        ], [
            'saveAutoPartsWarehouseCommandHandler' => 'App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\CommandsAutoPartsWarehouse\\SaveAutoPartsWarehouseCommand\\SaveAutoPartsWarehouseCommandHandler',
            'adapterAutoPartsWarehousePartNumbersInterface' => '?',
        ]))->withContext('App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\ApiAutoPartsWarehouse\\ControllerAutoPartsWarehouse\\AutoPartsWarehouseController::saveAutoPartsManually()', $container);
    }
}
