<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddCartAutoPartsCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\ApplicationSales\CommandsSales\AddCartAutoPartsCommand\AddCartAutoPartsCommandHandler' shared autowired service.
     *
     * @return \App\Sales\ApplicationSales\CommandsSales\AddCartAutoPartsCommand\AddCartAutoPartsCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/CommandsSales/AddCartAutoPartsCommand/AddCartAutoPartsCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/DomainSales/DomainModelSales/AutoPartsSold.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/ErrorsSales/InputErrorsSales.php';

        return $container->privates['App\\Sales\\ApplicationSales\\CommandsSales\\AddCartAutoPartsCommand\\AddCartAutoPartsCommandHandler'] = new \App\Sales\ApplicationSales\CommandsSales\AddCartAutoPartsCommand\AddCartAutoPartsCommandHandler(($container->privates['App\\Sales\\ApplicationSales\\ErrorsSales\\InputErrorsSales'] ??= new \App\Sales\ApplicationSales\ErrorsSales\InputErrorsSales()), ($container->privates['App\\Sales\\InfrastructureSales\\RepositorySales\\AutoPartsSoldRepository'] ?? $container->load('getAutoPartsSoldRepositoryService')), new \App\Sales\DomainSales\DomainModelSales\AutoPartsSold());
    }
}
