<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutoPartsWarehouseControllersearchAutoPartsWarehouseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._OTuz.t.App\AutoPartsWarehouse\InfrastructureAutoPartsWarehouse\ApiAutoPartsWarehouse\ControllerAutoPartsWarehouse\AutoPartsWarehouseController::searchAutoPartsWarehouse()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._OTuz.t.App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\ApiAutoPartsWarehouse\\ControllerAutoPartsWarehouse\\AutoPartsWarehouseController::searchAutoPartsWarehouse()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findByAutoPartsWarehouseQueryHandler' => ['privates', 'App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\QueryAutoPartsWarehouse\\SearchAutoPartsWarehouseQuery\\FindByAutoPartsWarehouseQueryHandler', 'getFindByAutoPartsWarehouseQueryHandlerService', true],
        ], [
            'findByAutoPartsWarehouseQueryHandler' => 'App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\QueryAutoPartsWarehouse\\SearchAutoPartsWarehouseQuery\\FindByAutoPartsWarehouseQueryHandler',
        ]))->withContext('App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\ApiAutoPartsWarehouse\\ControllerAutoPartsWarehouse\\AutoPartsWarehouseController::searchAutoPartsWarehouse()', $container);
    }
}
