<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdapterAutoPartsWarehouseSalesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\InfrastructureSales\ApiSales\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehouseSales' shared autowired service.
     *
     * @return \App\Sales\InfrastructureSales\ApiSales\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehouseSales
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sales/InfrastructureSales/ApiSales/AdapterAutoPartsWarehouse/AdapterAutoPartsWarehouseSalesInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/InfrastructureSales/ApiSales/AdapterAutoPartsWarehouse/AdapterAutoPartsWarehouseSales.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/QuerySales/SalesDeleteEditAutoPartsWarehouse/SalesDeleteEditAutoPartsWarehouseQueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/ErrorsSales/InputErrorsSales.php';

        return $container->privates['App\\Sales\\InfrastructureSales\\ApiSales\\AdapterAutoPartsWarehouse\\AdapterAutoPartsWarehouseSales'] = new \App\Sales\InfrastructureSales\ApiSales\AdapterAutoPartsWarehouse\AdapterAutoPartsWarehouseSales(new \App\Sales\ApplicationSales\QuerySales\SalesDeleteEditAutoPartsWarehouse\SalesDeleteEditAutoPartsWarehouseQueryHandler(($container->privates['App\\Sales\\ApplicationSales\\ErrorsSales\\InputErrorsSales'] ??= new \App\Sales\ApplicationSales\ErrorsSales\InputErrorsSales()), ($container->privates['App\\Sales\\InfrastructureSales\\RepositorySales\\AutoPartsSoldRepository'] ?? $container->load('getAutoPartsSoldRepositoryService'))));
    }
}
