<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterpartyControllereditCounterpartyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fdRb4Tu.App\Counterparty\InfrastructureCounterparty\ApiCounterparty\ControllerCounterparty\CounterpartyController::editCounterparty()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fdRb4Tu.App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController::editCounterparty()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findIdCounterpartyQueryHandler' => ['privates', 'App\\Counterparty\\ApplicationCounterparty\\QueryCounterparty\\EditCounterpartyQuery\\FindIdCounterpartyQueryHandler', 'getFindIdCounterpartyQueryHandlerService', true],
            'editCounterpartyCommandHandler' => ['privates', 'App\\Counterparty\\ApplicationCounterparty\\CommandsCounterparty\\EditCounterpartyCommand\\EditCounterpartyCommandHandler', 'getEditCounterpartyCommandHandlerService', true],
        ], [
            'findIdCounterpartyQueryHandler' => 'App\\Counterparty\\ApplicationCounterparty\\QueryCounterparty\\EditCounterpartyQuery\\FindIdCounterpartyQueryHandler',
            'editCounterpartyCommandHandler' => 'App\\Counterparty\\ApplicationCounterparty\\CommandsCounterparty\\EditCounterpartyCommand\\EditCounterpartyCommandHandler',
        ]))->withContext('App\\Counterparty\\InfrastructureCounterparty\\ApiCounterparty\\ControllerCounterparty\\CounterpartyController::editCounterparty()', $container);
    }
}
