<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeletePartNumbersCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\DeletePartNumbersCommand\DeletePartNumbersCommandHandler' shared autowired service.
     *
     * @return \App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\DeletePartNumbersCommand\DeletePartNumbersCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/CommandsPartNumbers/DeletePartNumbersCommand/DeletePartNumbersCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/ErrorsPartNumbers/InputErrorsPartNumbers.php';

        return $container->privates['App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\DeletePartNumbersCommand\\DeletePartNumbersCommandHandler'] = new \App\PartNumbers\ApplicationPartNumbers\CommandsPartNumbers\DeletePartNumbersCommand\DeletePartNumbersCommandHandler(($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\ErrorsPartNumbers\\InputErrorsPartNumbers'] ??= new \App\PartNumbers\ApplicationPartNumbers\ErrorsPartNumbers\InputErrorsPartNumbers()), ($container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\RepositoryPartNumbers\\PartNumbersFromManufacturersRepository'] ?? $container->load('getPartNumbersFromManufacturersRepositoryService')), ($container->privates['App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\RepositoryAutoPartsWarehouse\\AutoPartsWarehouseRepository'] ?? $container->load('getAutoPartsWarehouseRepositoryService')));
    }
}
