<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditCartPartsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\InfrastructureSales\ApiSales\FormSales\EditCartPartsType' shared autowired service.
     *
     * @return \App\Sales\InfrastructureSales\ApiSales\FormSales\EditCartPartsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/InfrastructureSales/ApiSales/FormSales/EditCartPartsType.php';

        return $container->privates['App\\Sales\\InfrastructureSales\\ApiSales\\FormSales\\EditCartPartsType'] = new \App\Sales\InfrastructureSales\ApiSales\FormSales\EditCartPartsType();
    }
}
