<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditCartAutoPartsCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\ApplicationSales\CommandsSales\EditCartAutoPartsCommand\EditCartAutoPartsCommandHandler' shared autowired service.
     *
     * @return \App\Sales\ApplicationSales\CommandsSales\EditCartAutoPartsCommand\EditCartAutoPartsCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/CommandsSales/EditCartAutoPartsCommand/EditCartAutoPartsCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/ErrorsSales/InputErrorsSales.php';

        return $container->privates['App\\Sales\\ApplicationSales\\CommandsSales\\EditCartAutoPartsCommand\\EditCartAutoPartsCommandHandler'] = new \App\Sales\ApplicationSales\CommandsSales\EditCartAutoPartsCommand\EditCartAutoPartsCommandHandler(($container->privates['App\\Sales\\ApplicationSales\\ErrorsSales\\InputErrorsSales'] ??= new \App\Sales\ApplicationSales\ErrorsSales\InputErrorsSales()), ($container->privates['App\\Sales\\InfrastructureSales\\RepositorySales\\AutoPartsSoldRepository'] ?? $container->load('getAutoPartsSoldRepositoryService')));
    }
}
