<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindOneByPaymentMethodQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\SearchAutoPartsWarehouseQuery\FindOneByPaymentMethodQueryHandler' shared autowired service.
     *
     * @return \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\SearchAutoPartsWarehouseQuery\FindOneByPaymentMethodQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/ApplicationAutoPartsWarehouse/QueryAutoPartsWarehouse/SearchAutoPartsWarehouseQuery/FindOneByPaymentMethodQueryHandler.php';

        return $container->privates['App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\QueryAutoPartsWarehouse\\SearchAutoPartsWarehouseQuery\\FindOneByPaymentMethodQueryHandler'] = new \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\QueryAutoPartsWarehouse\SearchAutoPartsWarehouseQuery\FindOneByPaymentMethodQueryHandler(($container->privates['App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\RepositoryAutoPartsWarehouse\\PaymentMethodRepository'] ?? $container->load('getPaymentMethodRepositoryService')));
    }
}
