<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindByCounterpartyQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Counterparty\ApplicationCounterparty\QueryCounterparty\SearchCounterpartyQuery\FindByCounterpartyQueryHandler' shared autowired service.
     *
     * @return \App\Counterparty\ApplicationCounterparty\QueryCounterparty\SearchCounterpartyQuery\FindByCounterpartyQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Counterparty/ApplicationCounterparty/QueryCounterparty/SearchCounterpartyQuery/FindByCounterpartyQueryHandler.php';

        return $container->privates['App\\Counterparty\\ApplicationCounterparty\\QueryCounterparty\\SearchCounterpartyQuery\\FindByCounterpartyQueryHandler'] = new \App\Counterparty\ApplicationCounterparty\QueryCounterparty\SearchCounterpartyQuery\FindByCounterpartyQueryHandler(($container->privates['App\\Counterparty\\InfrastructureCounterparty\\RepositoryCounterparty\\CounterpartyRepository'] ?? $container->load('getCounterpartyRepositoryService')));
    }
}
