<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAllPartNumbersQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PartNumbers\ApplicationPartNumbers\QueryPartNumbers\SearchPartNumbersQuery\FindAllPartNumbersQueryHandler' shared autowired service.
     *
     * @return \App\PartNumbers\ApplicationPartNumbers\QueryPartNumbers\SearchPartNumbersQuery\FindAllPartNumbersQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/QueryPartNumbers/SearchPartNumbersQuery/FindAllPartNumbersQueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/PartNumbers/ApplicationPartNumbers/ErrorsPartNumbers/InputErrorsPartNumbers.php';

        return $container->privates['App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindAllPartNumbersQueryHandler'] = new \App\PartNumbers\ApplicationPartNumbers\QueryPartNumbers\SearchPartNumbersQuery\FindAllPartNumbersQueryHandler(($container->privates['App\\PartNumbers\\ApplicationPartNumbers\\ErrorsPartNumbers\\InputErrorsPartNumbers'] ??= new \App\PartNumbers\ApplicationPartNumbers\ErrorsPartNumbers\InputErrorsPartNumbers()), ($container->privates['App\\PartNumbers\\InfrastructurePartNumbers\\RepositoryPartNumbers\\PartNumbersFromManufacturersRepository'] ?? $container->load('getPartNumbersFromManufacturersRepositoryService')));
    }
}
