<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindBySalesToDateQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sales\ApplicationSales\QuerySales\SalesToDate\FindBySalesToDateQueryHandler' shared autowired service.
     *
     * @return \App\Sales\ApplicationSales\QuerySales\SalesToDate\FindBySalesToDateQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sales/ApplicationSales/QuerySales/SalesToDate/FindBySalesToDateQueryHandler.php';

        return $container->privates['App\\Sales\\ApplicationSales\\QuerySales\\SalesToDate\\FindBySalesToDateQueryHandler'] = new \App\Sales\ApplicationSales\QuerySales\SalesToDate\FindBySalesToDateQueryHandler(($container->privates['App\\Sales\\InfrastructureSales\\RepositorySales\\AutoPartsSoldRepository'] ?? $container->load('getAutoPartsSoldRepositoryService')));
    }
}
