<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFactoryReadingEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\AutoPartsWarehouse\DomainAutoPartsWarehouse\Factory\FactoryReadingEmail' shared autowired service.
     *
     * @return \App\AutoPartsWarehouse\DomainAutoPartsWarehouse\Factory\FactoryReadingEmail
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/DomainAutoPartsWarehouse/Factory/FactoryReadingEmail.php';

        return $container->privates['App\\AutoPartsWarehouse\\DomainAutoPartsWarehouse\\Factory\\FactoryReadingEmail'] = new \App\AutoPartsWarehouse\DomainAutoPartsWarehouse\Factory\FactoryReadingEmail();
    }
}
