<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HWI0Oe0.Symfony\Component\HttpKernel\Exception\HttpException' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Exception\HttpException
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HWI0Oe0": it references class "Symfony\\Component\\HttpKernel\\Exception\\HttpException" but no such service exists.');
    }
}
