<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartNumbersControllereditPartNumbersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0DLOJnw.App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\ControllerPartNumbers\PartNumbersController::editPartNumbers()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0DLOJnw.App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\ControllerPartNumbers\\PartNumbersController::editPartNumbers()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findIdPartNumbersQueryHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\EditPartNumbersQuery\\FindIdPartNumbersQueryHandler', 'getFindIdPartNumbersQueryHandlerService', true],
            'editPartNumbersCommandHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\EditPartNumbersCommand\\EditPartNumbersCommandHandler', 'getEditPartNumbersCommandHandlerService', true],
            'findOneByOriginalRoomsQueryHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindOneByOriginalRoomsQueryHandler', 'getFindOneByOriginalRoomsQueryHandlerService', true],
            'editOriginalRoomsCommandHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\EditPartNumbersCommand\\EditOriginalRoomsCommandHandler', 'getEditOriginalRoomsCommandHandlerService', true],
            'saveOriginalRoomsCommandHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\SavePartNumbersCommand\\SaveOriginalRoomsCommandHandler', 'getSaveOriginalRoomsCommandHandlerService', true],
            'errorMessageViaSession' => ['services', 'App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession', 'getErrorMessageViaSessionService', true],
        ], [
            'findIdPartNumbersQueryHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\EditPartNumbersQuery\\FindIdPartNumbersQueryHandler',
            'editPartNumbersCommandHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\EditPartNumbersCommand\\EditPartNumbersCommandHandler',
            'findOneByOriginalRoomsQueryHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindOneByOriginalRoomsQueryHandler',
            'editOriginalRoomsCommandHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\EditPartNumbersCommand\\EditOriginalRoomsCommandHandler',
            'saveOriginalRoomsCommandHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\CommandsPartNumbers\\SavePartNumbersCommand\\SaveOriginalRoomsCommandHandler',
            'errorMessageViaSession' => 'App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession',
        ]))->withContext('App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\ControllerPartNumbers\\PartNumbersController::editPartNumbers()', $container);
    }
}
