<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartNumbersControllersearchPartNumbersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LwfFijC.App\PartNumbers\InfrastructurePartNumbers\ApiPartNumbers\ControllerPartNumbers\PartNumbersController::searchPartNumbers()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LwfFijC.App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\ControllerPartNumbers\\PartNumbersController::searchPartNumbers()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findAllPartNumbersQueryHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindAllPartNumbersQueryHandler', 'getFindAllPartNumbersQueryHandlerService', true],
            'searchPartNumbersQueryHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\SearchPartNumbersQueryHandler', 'getSearchPartNumbersQueryHandlerService', true],
            'findOneByOriginalRoomsQueryHandler' => ['privates', 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindOneByOriginalRoomsQueryHandler', 'getFindOneByOriginalRoomsQueryHandlerService', true],
            'errorMessageViaSession' => ['services', 'App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession', 'getErrorMessageViaSessionService', true],
        ], [
            'findAllPartNumbersQueryHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindAllPartNumbersQueryHandler',
            'searchPartNumbersQueryHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\SearchPartNumbersQueryHandler',
            'findOneByOriginalRoomsQueryHandler' => 'App\\PartNumbers\\ApplicationPartNumbers\\QueryPartNumbers\\SearchPartNumbersQuery\\FindOneByOriginalRoomsQueryHandler',
            'errorMessageViaSession' => 'App\\PartNumbers\\InfrastructurePartNumbers\\ErrorMessageViaSession\\ErrorMessageViaSession',
        ]))->withContext('App\\PartNumbers\\InfrastructurePartNumbers\\ApiPartNumbers\\ControllerPartNumbers\\PartNumbersController::searchPartNumbers()', $container);
    }
}
