<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllerdeleteСartAutoPartsWarehouseSoldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nLrSUG4.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::deleteСartAutoPartsWarehouseSold()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nLrSUG4.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::deleteСartAutoPartsWarehouseSold()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteCartAutoPartsCommandHandler' => ['privates', 'App\\Sales\\ApplicationSales\\CommandsSales\\DeleteCartAutoPartsCommand\\DeleteCartAutoPartsCommandHandler', 'getDeleteCartAutoPartsCommandHandlerService', true],
        ], [
            'deleteCartAutoPartsCommandHandler' => 'App\\Sales\\ApplicationSales\\CommandsSales\\DeleteCartAutoPartsCommand\\DeleteCartAutoPartsCommandHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::deleteСartAutoPartsWarehouseSold()', $container);
    }
}
