<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecit_Imap_Connection_ExampleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'secit.imap.connection.example' shared service.
     *
     * @return \SecIT\ImapBundle\Connection\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/secit-pl/imap-bundle/Connection/ConnectionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/secit-pl/imap-bundle/Connection/Connection.php';

        return $container->privates['secit.imap.connection.example'] = new \SecIT\ImapBundle\Connection\Connection('example', '{imap.mail.ru:993/imap/ssl/novalidate-cert}INBOX', 'imap_test_test_test@mail.ru', 'jVRBymTQUhzvExwcka67', 'UTF-8', NULL, true, 770, true);
    }
}
