<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaveAutoPartsWarehouseCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\CommandsAutoPartsWarehouse\SaveAutoPartsWarehouseCommand\SaveAutoPartsWarehouseCommandHandler' shared autowired service.
     *
     * @return \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\CommandsAutoPartsWarehouse\SaveAutoPartsWarehouseCommand\SaveAutoPartsWarehouseCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/ApplicationAutoPartsWarehouse/CommandsAutoPartsWarehouse/SaveAutoPartsWarehouseCommand/SaveAutoPartsWarehouseCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/DomainAutoPartsWarehouse/DomainModelAutoPartsWarehouse/EntityAutoPartsWarehouse/AutoPartsWarehouse.php';
        include_once \dirname(__DIR__, 4).'/src/AutoPartsWarehouse/ApplicationAutoPartsWarehouse/ErrorsAutoPartsWarehouse/InputErrorsAutoPartsWarehouse.php';

        return $container->privates['App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\CommandsAutoPartsWarehouse\\SaveAutoPartsWarehouseCommand\\SaveAutoPartsWarehouseCommandHandler'] = new \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\CommandsAutoPartsWarehouse\SaveAutoPartsWarehouseCommand\SaveAutoPartsWarehouseCommandHandler(($container->privates['App\\AutoPartsWarehouse\\ApplicationAutoPartsWarehouse\\ErrorsAutoPartsWarehouse\\InputErrorsAutoPartsWarehouse'] ??= new \App\AutoPartsWarehouse\ApplicationAutoPartsWarehouse\ErrorsAutoPartsWarehouse\InputErrorsAutoPartsWarehouse()), ($container->privates['App\\AutoPartsWarehouse\\InfrastructureAutoPartsWarehouse\\RepositoryAutoPartsWarehouse\\AutoPartsWarehouseRepository'] ?? $container->load('getAutoPartsWarehouseRepositoryService')), new \App\AutoPartsWarehouse\DomainAutoPartsWarehouse\DomainModelAutoPartsWarehouse\EntityAutoPartsWarehouse\AutoPartsWarehouse());
    }
}
