<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController' shared autowired service.
     *
     * @return \App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Sales/InfrastructureSales/ApiSales/ControllerSales/SalesController.php';

        $container->services['App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController'] = $instance = new \App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController', $container));

        return $instance;
    }
}
