<?php

namespace ContainerRunraoK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalesControllercartWarehouseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qF_iV2q.App\Sales\InfrastructureSales\ApiSales\ControllerSales\SalesController::cartWarehouse()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qF_iV2q.App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::cartWarehouse()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findByCartAutoPartsSoldQueryHandler' => ['privates', 'App\\Sales\\ApplicationSales\\QuerySales\\ListCartAutoParts\\FindByCartAutoPartsSoldQueryHandler', 'getFindByCartAutoPartsSoldQueryHandlerService', true],
        ], [
            'findByCartAutoPartsSoldQueryHandler' => 'App\\Sales\\ApplicationSales\\QuerySales\\ListCartAutoParts\\FindByCartAutoPartsSoldQueryHandler',
        ]))->withContext('App\\Sales\\InfrastructureSales\\ApiSales\\ControllerSales\\SalesController::cartWarehouse()', $container);
    }
}
