<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM9s1qO5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM9s1qO5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM9s1qO5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM9s1qO5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM9s1qO5\App_KernelDevDebugContainer([
    'container.build_hash' => 'M9s1qO5',
    'container.build_id' => 'e3fe1952',
    'container.build_time' => 1739959997,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM9s1qO5');
